spring.application.name=trabajo
springdoc.show-actuator=false
springdoc.writer-with-default-pretty-printer=true
springdoc.show-login-endpoint=true
springdoc.packages-to-scan=com.tt1.trabajo
springdoc.swagger-ui.path=/swagger/index.html
